gameathon_tracker/awards/urls.py
from django.urls import path
from .views import load_players, award_points


urlpatterns = [
    path('', award_points, name='awards'),
    path('load_players/', load_players, name='load_players'),
]

gameathon_tracker/gameathon_tracker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gameboard.urls')),
    path('awards/', include('awards.urls')),
    path('players/', include('django.contrib.auth.urls')),
    path('players/', include('players.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameathon_tracker/awards/models.py
from django.db import models
from django.urls import reverse

class Award(models.Model):
    player_gameboard_id = models.ForeignKey('gameboard.PlayerGameboard', on_delete=models.CASCADE, related_name='player_gameboard')
    game_name = models.CharField(max_length=200)
    position = models.IntegerField()
    team_game = models.BooleanField()
    points_awarded = models.IntegerField()
    award_created_at = models.DateTimeField(auto_now_add=True)

    #this defines where to redirect after a form submit
    def get_absolute_url(self):
        return reverse('awards')

gameathon_tracker/awards/forms.py
from django import forms
from gameboard.models import PlayerGameboard, Gameboard
from django.contrib.auth.models import User


class AwardForm(forms.Form):
    gameboard = forms.ModelChoiceField(queryset=Gameboard.objects.none(),
                                       label='Choose Gameboard',
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    player = forms.ModelChoiceField(queryset=User.objects.none(),
                                    label='Player:',
                                    widget=forms.Select(attrs={'class': 'form-control'}))
    game_name = forms.CharField(label='What game did you play?',
                                max_length=200,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    position = forms.IntegerField(label='Place #',
                                  widget=forms.NumberInput(attrs={'class': 'form-control'}))
    team_game = forms.BooleanField(label='Team Game?',
                                   required=False,
                                   widget=forms.CheckboxInput(attrs={'class': 'form-control'}))
    points_awarded = forms.IntegerField(label='Points',
                                        widget=forms.NumberInput(attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        super(AwardForm, self).__init__(*args, **kwargs)
        self.fields['gameboard'] = forms.ModelChoiceField(queryset=Gameboard.objects.filter(gameboard_players=user),
                                                          label='Choose Gameboard',
                                                          widget=forms.Select(attrs={'class': 'form-control'}))

gameathon_tracker/awards/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Award
from .forms import AwardForm
from gameboard.models import PlayerGameboard, Gameboard
from django.contrib.auth.models import User


def award_points(request):
    form_class = AwardForm
    if request.POST:
        form = form_class(request.user, request.POST)
        if request.method == 'POST':
            if form.is_valid():
                obj = Award()
                obj.player_gameboard_id = PlayerGameboard.objects.get(player_id=form.cleaned_data['player'],
                                                                      gameboard_id=form.cleaned_data['gameboard'])
                obj.position = form.cleaned_data['position']
                obj.points_awarded = form.cleaned_data['points_awarded']
                obj.team_game = form.cleaned_data['team_game']
                obj.game_name = form.cleaned_data['game_name']
                obj.save()
                return HttpResponseRedirect(reverse('gameboard'))
    else:
        form = form_class(request.user)

    return render(request, "awards/award_points.html", {'form': form})


def load_players(request):
    gameboard_id = request.GET.get('gameboard_id')
    players = User.objects.filter(playergameboard__gameboard_id=gameboard_id)
    return render(request, "awards/load_players.html", {'players': players})

gameathon_tracker/awards/templates/awards/award_points.html
{% extends "base.html" %}

{% block title %}Award Points{% endblock %}

{% block content %}
<h1 class="text-center">Award Points</h1>

<form method="POST" id="awardForm" class="text-center border border-light p-5" action="#!"
      data-players-url="{% url 'load_players' %}">
    {% csrf_token %}


    <label for="{{ form.gameboard.id_for_label }}">Choose a gameboard:</label>
    {{ form.gameboard }}

    <br>

    <div class="form-row mb-4">
        <div class="col">
            {{ form.player.label}}
            {{ form.player }}
        </div>
        <div class="col">
            {{ form.position.label}}
            {{ form.position }}
        </div>
        <div class="col">
            {{ form.points_awarded.label}}
            {{ form.points_awarded }}
        </div>
    </div>
    <div>
        {{ form.team_game.label}}
        {{ form.team_game }}
    </div>
    <br/>
    <div>
        {{ form.game_name.label}}
        {{ form.game_name }}
    </div>


    <br/><br/>
    <button class="btn btn-info btn-block" type="submit">Award Points</button>

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_gameboard").change(function() {
        const url = $("#awardForm").attr("data-players-url");
        const gameboardId = $(this).val()

        $.ajax({
            url:url,
            data: {
                'gameboard_id': gameboardId
            },
            success: function(data) {
                console.log(data);
                $("#id_player").html(data);
            }
        });
    });


</script>

{% endblock %}

gameathon_tracker/awards/templates/awards/awardpoints.html
{% extends "base.html" %}

{% block title %}Award Points{% endblock %}

{% block content %}
    <h1>This is where we will award points.</h1>



    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Points to Gameboard</button>
    </form>

    <hr>

    {% for record in test_query %}
        {{ record.player_gameboard_id }}
    {% endfor %}

{% endblock %}

gameathon_tracker/awards/templates/awards/load_players.html
<option value="">-----</option>
{% for player in players %}
<option value="{{ player.pk }}">{{ player.username }}</option>
{% endfor %}

gameathon_tracker/awards/templates/awards/test.html
{% extends "base.html" %}

{% block title %}Test{% endblock %}

{% block content %}
<h2>Points Form</h2>

 <!-- Default form contact -->
    <form method="post" id="awardForm" class="text-center border border-light p-5" action="#!" data-players-url="{% url 'load_players' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p class="h4 mb-4">Award Points</p>
        {{ form.management_form }}
        <!-- Gameboard -->
        <label for="{{ form.gameboard.id_for_label }}">Gameboard</label>
        {{ form.gameboard }}

        <br>

        <div class="form-row mb-4">
            <div class="col">
                <!-- Player -->

                {{ form.player }}
            </div>
            <div class="col">
                <!-- Place -->
                {{ form.position }}
            </div>
            <div class="col">
                <!-- Points -->
                {{ form.points_awarded }}
            </div>
            <div class="col">
                <!-- Last name -->

               {{ form.team_game }}
            </div>
        </div>

        <!-- Name -->
        {{ form.game_name }}


        <!-- Send button -->
        <button class="btn btn-info btn-block" type="submit">Send</button>

    </form>
<!-- Default form contact -->
<script src ="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_gameboard").change(function() {
        const url = $("#awardForm").attr("data-players-url");
        const gameboardId = $(this).val()

        $.ajax({
            url:url,
            data: {
                'gameboard_id': gameboardId
            },
            success: function(data) {
                console.log(data);
                $("#id_player").html(data);
            }
        });
    });
</script>

{% endblock %}